namespace ModelsUpgrade.Shared;
public enum Currency
{
    None,
    AED,  // United Arab Emirates Dirham (UAE)
    DZD,  // Algerian Dinar (Algeria)
    BHD,  // Bahraini Dinar (Bahrain)
    EGP,  // Egyptian Pound (Egypt)
    IQD,  // Iraqi Dinar (Iraq)
    JOD,  // Jordanian Dinar (Jordan)
    KWD,  // Kuwaiti Dinar (Kuwait)
    LBP,  // Lebanese Pound (Lebanon)
    LYD,  // Libyan Dinar (Libya)
    MAD,  // Moroccan Dirham (Morocco)
    OMR,  // Omani Rial (Oman)
    QAR,  // Qatari Riyal (Qatar)
    SAR,  // Saudi Riyal (Saudi Arabia)
    SDG,  // Sudanese Pound (Sudan)
    SYP,  // Syrian Pound (Syria)
    TND,  // Tunisian Dinar (Tunisia)
    YER,  // Yemeni Rial (Yemen)
    EUR,  // Euro (European Union)
    GBP,  // British Pound (United Kingdom)
    CHF,  // Swiss Franc (Switzerland)
    NOK,  // Norwegian Krone (Norway)
    SEK,  // Swedish Krona (Sweden)
    DKK,  // Danish Krone (Denmark)
    HRK,  // Croatian Kuna (Croatia)
    HUF,  // Hungarian Forint (Hungary)
    CZK,  // Czech Koruna (Czech Republic)
    PLN,  // Polish Zloty (Poland)
    RON,  // Romanian Leu (Romania)
    BGN,  // Bulgarian Lev (Bulgaria)
    TRY,  // Turkish Lira (Turkey)
    ISK,  // Icelandic Króna (Iceland)
    USD,  // United States Dollar (USA)
    CAD,  // Canadian Dollar (Canada)
    MXN,  // Mexican Peso (Mexico)
    ARS,  // Argentine Peso (Argentina)
    BRL,  // Brazilian Real (Brazil)
    CLP,  // Chilean Peso (Chile)
    COP,  // Colombian Peso (Colombia)
    PEN,  // Peruvian Nuevo Sol (Peru)
    UYU,  // Uruguayan Peso (Uruguay)
    BOB,  // Bolivian Boliviano (Bolivia)
    SVC,  // Salvadoran Colón (El Salvador)
    GTQ,  // Guatemalan Quetzal (Guatemala)
    CNY,  // Chinese Yuan (China)
    JPY,  // Japanese Yen (Japan)
    INR,  // Indian Rupee (India)
    KRW,  // South Korean Won (South Korea)
    ZAR,  // South African Rand (South Africa)
    AUD,  // Australian Dollar (Australia)
    SGD,  // Singapore Dollar (Singapore)
    NZD,  // New Zealand Dollar (New Zealand)
    TWD,  // New Taiwan Dollar (Taiwan)
    THB,  // Thai Baht (Thailand)
    MYR,  // Malaysian Ringgit (Malaysia)
    IDR,  // Indonesian Rupiah (Indonesia)
    VND,  // Vietnamese Dong (Vietnam)
}

